# Generated by Django 4.1.1 on 2024-10-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_alter_directorgeneral_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='clave_id',
            field=models.IntegerField(default=0),
        ),
    ]
